local defaults = {
    debug_enabled = true,
}

function get_config(key)
    if ui_mcm then
        local value = ui_mcm.get("zone_frontier/" .. key)
        if value ~= nil then
            return value
        end
    end

    return defaults[key]
end

function on_mcm_load()
    return {
        id = "zone_frontier",
        sh = true,
        gr = {
            {
                id = "title",
                type = "slide",
                link = "ui_options_slider_player",
                text = "ui_mcm_zone_frontier_title",
                size = {512, 50},
                spacing = 20,
            },
            {
                id = "debug_enabled",
                type = "check",
                val = 1,
                def = defaults.debug_enabled,
            },
        },
    }
end
